# Generated by Django 6.0.1 on 2026-01-23 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30)),
                ('group_day', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('group_time', models.TimeField()),
                ('group_start_date', models.DateField()),
                ('group_session_count', models.IntegerField()),
                ('group_is_active', models.BooleanField(default=True)),
                ('group_is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.IntegerField()),
                ('session_date', models.DateField()),
                ('session_time', models.TimeField()),
                ('status', models.CharField(choices=[('delayed', 'Delayed'), ('done', 'Done'), ('scheduled', 'Scheduled'), ('canceled', 'Canceled')], default='scheduled', max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('homework_info', models.TextField(blank=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='groups.groups')),
            ],
            options={
                'ordering': ['session_number'],
                'unique_together': {('group', 'session_number')},
            },
        ),
        migrations.CreateModel(
            name='HomeworkImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=30)),
                ('comment', models.TextField()),
                ('extra_task', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworkImages', to='groups.session')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('full_name', models.CharField(max_length=30)),
                ('total_grade', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='groups.groups')),
            ],
        ),
    ]
