# Generated by Django 6.0.1 on 2026-01-24 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('is_late', models.BooleanField(default=False)),
                ('lost_connection', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('homework_done', models.BooleanField(default=False)),
                ('improvment_note', models.CharField(blank=True, max_length=50)),
                ('feedback', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='groups.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='groups.student')),
            ],
            options={
                'unique_together': {('session', 'student')},
            },
        ),
    ]
