# Generated by Django 6.0.1 on 2026-02-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_gradebook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradebook',
            options={'ordering': ['session__session_number']},
        ),
        migrations.AlterField(
            model_name='homeworkimages',
            name='image',
            field=models.ImageField(upload_to='my_homeworks'),
        ),
    ]
