# Generated by Django 6.0.1 on 2026-02-17 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_student_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('delayed', 'Delayed'), ('done', 'Done'), ('scheduled', 'Scheduled'), ('canceled', 'Canceled'), ('active', 'Active')], default='scheduled', max_length=30),
        ),
        migrations.CreateModel(
            name='StudentSessionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_score', to='groups.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_score', to='groups.student')),
            ],
            options={
                'unique_together': {('student', 'session')},
            },
        ),
        migrations.AddField(
            model_name='session',
            name='students',
            field=models.ManyToManyField(through='groups.StudentSessionScore', to='groups.student'),
        ),
    ]
